Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0977428/ml_models/unet/segmentation/train.py", line 2, in <module>
    from config import config
  File "/uufs/chpc.utah.edu/common/home/u0977428/ml_models/unet/segmentation/config.py", line 133, in <module>
    power_jaccard = PowerJaccardLoss(config['model']['out_channels'], weights=weights, power=1.5)
  File "/uufs/chpc.utah.edu/common/home/u0977428/ml_models/base/loss.py", line 66, in __init__
    self.register_buffer('weights', self.weights)
  File "/uufs/chpc.utah.edu/common/home/u0977428/.micromamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 535, in register_buffer
    raise KeyError(f"attribute '{name}' already exists")
KeyError: "attribute 'weights' already exists"
