Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0977428/.micromamba/lib/python3.10/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/uufs/chpc.utah.edu/common/home/u0977428/.micromamba/lib/python3.10/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/uufs/chpc.utah.edu/common/home/u0977428/.micromamba/lib/python3.10/site-packages/toml/decoder.py", line 907, in load_value
    raise ValueError("This float is missing digits after "
ValueError: This float is missing digits after the point

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0977428/ml_models/unet/segmentation/train.py", line 2, in <module>
    from config import config
  File "/uufs/chpc.utah.edu/common/home/u0977428/ml_models/unet/segmentation/config.py", line 113, in <module>
    config.load(path.join(path.dirname(__file__), 'config.toml'))
  File "/uufs/chpc.utah.edu/common/home/u0977428/ml_models/unet/segmentation/config.py", line 51, in load
    toml_dict = toml.load(path)
  File "/uufs/chpc.utah.edu/common/home/u0977428/.micromamba/lib/python3.10/site-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "/uufs/chpc.utah.edu/common/home/u0977428/.micromamba/lib/python3.10/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float is missing digits after the point (line 4 column 1 char 30)
